[project]
name = "pyms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cursor>=1.3.5",
    "mutagen>=1.47.0",
    "pygame>=2.6.1",
    "pynput>=1.8.1",
]
